# Generated by Django 6.1.1 on 2026-09-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("seed_url", models.URLField(max_length=1000)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pages_crawled", models.PositiveIntegerField(default=0)),
                ("critical_issues", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_runs",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "site_health_crawl_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawledPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("status_code", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical", models.CharField(blank=True, max_length=1000)),
                ("noindex", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                (
                    "crawl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="site_health.crawlrun",
                    ),
                ),
            ],
            options={
                "db_table": "site_health_crawled_page",
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("category", models.CharField(max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
                (
                    "crawl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="site_health.crawlrun",
                    ),
                ),
            ],
            options={
                "db_table": "site_health_finding",
            },
        ),
    ]
