# Generated by Django 6.1.1 on 2026-09-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(max_length=500)),
                ('access_token_enc', models.TextField()),
                ('refresh_token_enc', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('scope', models.CharField(max_length=300)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_console_connection', to='businesses.business')),
            ],
            options={
                'db_table': 'search_console_connection',
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleTopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=1000)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_console_top_pages', to='businesses.business')),
            ],
            options={
                'db_table': 'search_console_top_page',
                'ordering': ['-clicks'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleTopQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_console_top_queries', to='businesses.business')),
            ],
            options={
                'db_table': 'search_console_top_query',
                'ordering': ['-clicks'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_console_daily_metrics', to='businesses.business')),
            ],
            options={
                'db_table': 'search_console_daily_metric',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['business', '-date'], name='search_cons_busines_b6b2a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'date'), name='unique_business_date_metric')],
            },
        ),
    ]
