# Generated by Django 6.1.1 on 2026-10-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_id", models.CharField(max_length=32)),
                ("property_name", models.CharField(max_length=300)),
                ("account_id", models.CharField(blank=True, max_length=32)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("access_token_enc", models.TextField()),
                ("refresh_token_enc", models.TextField()),
                ("token_expires_at", models.DateTimeField()),
                ("scope", models.CharField(max_length=500)),
                ("conversion_events", models.JSONField(default=list)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_connection",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_connection",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_daily_metrics",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_daily_metric",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["business", "-date"],
                        name="analytics_d_busines_fc0de7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "date"),
                        name="unique_analytics_business_date",
                    )
                ],
            },
        ),
    ]
